### ISSUE TITLE
Akward information for git-cola

### ISSUE THREAD

**Issue by kafran** [ubuntu-mate/ubuntu-mate.software#1]
ubuntu-mate.software/source/apps/development/git-cola/metadata.json

Every link and information drives to git-scm, but the software is git-cola. I think git-scm and git-cola are different projects, no? Shouldn't it point to https://git-cola.github.io/ ?

**Comment by lah7** [comment]
Thanks for spotting that. They are different projects, but _it seems_ the intention for this entry was installing the latest Git along with a front-end.

For consistency, I've updated the website URL so it goes to the project's website. The data in this repository is not yet live, so I've also committed for the current "stable" Welcome/Boutique: https://github.com/ubuntu-mate/ubuntu-mate-welcome/commit/104aa992234ef51a11422246bc47a02dd8d3a8dd
